// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZoyva4tvBBYqi6JQ6EY6b9-4LGa_ykw',
    appId: '1:102233149888:android:2838492f5081e2c61f7825',
    messagingSenderId: '102233149888',
    projectId: 'sokoflow-5d830',
    storageBucket: 'sokoflow-5d830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuhfBRBHk-9kBg5i3cf5gtueVK3ru9LE8',
    appId: '1:102233149888:ios:c12d5f1879d927701f7825',
    messagingSenderId: '102233149888',
    projectId: 'sokoflow-5d830',
    storageBucket: 'sokoflow-5d830.appspot.com',
    androidClientId: '102233149888-sudt10t9enr2vo0llvahgqbrs5uf8aqg.apps.googleusercontent.com',
    iosClientId: '102233149888-uq64lr37ub96mo46adqnc34bv3r7hklk.apps.googleusercontent.com',
    iosBundleId: 'com.total.sokoflow.totalSokoflow',
  );
}
